config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :worklogs,          only: [:create, :destroy]
  resources :projects
  resources :implements
  resources :partakers
  resources :plans
  resources :partybs
  resources :contracts
  resources :deals
  resources :roles

end

app/models/contract.rb
require 'carrierwave/orm/activerecord'
class Contract < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :project
  belongs_to :partyb
  belongs_to :paytype
  has_many :deals
  default_scope -> { order(created_at: :desc) }
  
  validates_presence_of  :name, presence: true, :message => "合同名称不能为空！"
  validates_presence_of  :code, presence: true, :message => "合同代码不能为空！"
  validates_uniqueness_of :code, :message => "合同代码不能相同！"
  validates :total, numericality: { greater_than: 0 },  allow_blank: true
  validates :surplus, numericality: { greater_than: 0 },  allow_blank: true
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :user
  belongs_to :contract
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :implements
	
end

app/models/implement.rb
class Implement < ActiveRecord::Base
  belongs_to :project
  belongs_to :department
  validates :job, presence: true
  # validates :department_id , :uniqueness => {:scope => :project_id} 
  validates_uniqueness_of :department_id , :on => :create, :uniqueness => {:scope => :project_id} ,:message => "该部门已经分配任务！" 

end

app/models/partaker.rb
class Partaker < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  validates_uniqueness_of :user_id , :on => :create, :uniqueness => {:scope => :project_id} ,:message => "人员重复！" 
end

app/models/partyb.rb
class Partyb < ActiveRecord::Base
  has_many :contracts
  validates_presence_of  :name, presence: true, :message => "单位名称不能为空！"
  validates_uniqueness_of :name, :message => "单位名称不能相同！"
  validates_format_of :postcode, :with => /[0-9]/,  allow_blank: true,
    message: "邮编必须是数字组成！" 

  validates_format_of :account,:with => /[0-9]/,allow_blank: true,:message => "账户必须是数字组成！"
  validates_format_of :contacts_tel,:with => /[0-9]/, allow_blank: true,:message => "电话必须是数字组成！"
  validates_format_of :corporation_tel,:with => /[0-9]/,allow_blank: true,:message => "电话必须是数字组成！"
end

app/models/paytype.rb
class Paytype < ActiveRecord::Base
  has_many :contracts
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :project
  validates_uniqueness_of :name , :message => "计划步骤名称不能相同！"
  validates_presence_of :name, :message => "计划步骤名称不能为空" 
  validates_presence_of :content, :message => "计划步骤内容不能为空" 
  validate :plan_end_after_start

  private
  
	  #检查结束时间在开始时间之后.
	  def plan_end_after_start
		if start > plan_end
		   errors[:plan_end] << "结束时间需要在开始时间之后"
		end
	  end 
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :ProjectType
  belongs_to :ProjectStatus
  has_many :implements, dependent: :destroy
  has_many :partakers, dependent: :destroy
  has_many :plans, dependent: :destroy
  has_many :contracts
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates_presence_of :name, :message => "项目名称不能为空"
  validates_presence_of :code, :message => "项目编号不能为空"
  validates_uniqueness_of :code , :message => "项目编号必须唯一"
  validates_presence_of :user_id, :message => "项目负责人不能为空" 
  validates_presence_of :ProjectStatus_id, :message => "项目状态不能为空" 
  validates_presence_of :ProjectType_id, :message => "项目类型不能为空" 
  validates_presence_of :start_time, :message => "项目开始时间不能为空" 
  validate :end_time_after_start_time

  private
  
	  #检查结束时间在开始时间之后.
	  def end_time_after_start_time
		if start_time > end_time
		   errors[:end_time] << "结束时间需要在开始时间之后"
		end
	  end 

end

app/models/project_status.rb
class ProjectStatus < ActiveRecord::Base
   has_many :projects
end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
  has_many :projects
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
	validates_uniqueness_of :name , :message => "角色名称不能相同！"
	validates_uniqueness_of :id , :message => "角色ID不能相同！"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :worklogs, dependent: :destroy
  has_many :projects
  has_many :partakers
  belongs_to :role
  attr_accessor :remember_token
  before_save { self.name = name.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :namecn, presence: true, length: { maximum: 50 }
  validates :role_id, presence: true
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/worklog.rb
class Worklog < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @worklog = current_user.worklogs.build if logged_in?
  end
  def about
  end
  def contact
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/partybs_helper.rb
module PartybsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/_admin.html.erb
<section class="user_info">
	<h2>用户管理</h2>
	<h3>
		<%= link_to "管理用户", users_path %>|
		<%= link_to "注册用户", signup_path %>|
		<%= link_to "角色管理", roles_path %>|
	</h3>
 </section>

app/views/static_pages/_contract.html.erb
<section class="user_info">
	<h2>合同管理</h2>
	<h3>
		<%= link_to "合同清单", contracts_path %>
		<%= link_to "新建合同" ,new_contract_path %> |
		<%= link_to "业务往来单位信息记录", partybs_path %>	|
		<%= link_to "收/付款记录", deals_path %>	
	</h3>
</section>

app/views/static_pages/_project.html.erb
<section class="user_info">
	<h2>项目管理</h2>
	<h3>
		<%= link_to "项目清单", projects_path  %> |
		<%= link_to "新建项目", new_project_path  %> |
		<%= link_to "新建部门任务", new_implement_path  %> |
		<%= link_to "新建项目计划", new_plan_path %> |
		<%= link_to "新建项目参与人员", new_partaker_path  %>		
	</h3>
</section>

app/views/static_pages/about.html.erb
<div class="center jumbotron">

  <h2>
  项目管理登记系统是为了登记中心项目而建立...  
  </h2>


</div>

app/views/static_pages/contact.html.erb
<div class="center jumbotron">

  <h2>
  电话：66260025
  </h2>


</div>

app/views/static_pages/home.html.erb
<% provide(:title, "首页") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="worklog_form">
        <%= render 'shared/worklog_form' %>
      </section>
    </aside>
	
	<div class="col-md-7 col-md-offset-1">
	  <h3>
		<% case current_user.role_id %>
			<% when 0 %>
				<%= render 'admin'%>			
			<% when 1 %>
				<%= link_to "项目清单", projects_path  %> <br>	
				<%= link_to "合同清单", contracts_path %>			
			<% when 2 %>
				<%= link_to "项目清单", projects_path  %> <br>	
				<%= link_to "合同清单", contracts_path %>
			<% when 3 %>
				<%= link_to "项目清单", projects_path  %> <br>	
				<%= link_to "合同清单", contracts_path %>
			<% when 4 %>
				<%= link_to "项目清单", projects_path  %> <br>	
				<%= link_to "合同清单", contracts_path %> <br>
				<%= link_to "新建项目计划", new_plan_path %> <br>
				<%= link_to "新建项目参与人员", new_partaker_path %>
			<% when 5 %>
				<%= render 'project'%>
				<%= render 'contract'%>	
			<% when 6 %>
				<%= link_to "项目清单", projects_path  %> <br>	
				<%= link_to "合同清单", contracts_path %> <br>	
				<%= link_to "收/付款记录", deals_path %>
			<% when 7 %>
				<%= link_to "项目清单", projects_path  %> <br>	
				<%= link_to "合同清单", contracts_path %> <br>
				<%= link_to "新建项目", new_project_path  %> <br>
				<%= link_to "新建部门任务", new_implement_path  %> <br>
				<%= link_to "新建合同" ,new_contract_path %> <br>
				<%= link_to "业务往来单位信息记录", partybs_path %>				
		<% end %>
	  </h3>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
  <h1>欢迎使用项目管理登记系统</h1>
    <h2>
      项目首页
    </h2>
  </div>
<% end %>