config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :worklogs,          only: [:create, :destroy]
  resources :projects
  resources :implements
  resources :partakers
  resources :plans
  resources :partybs
  resources :contracts
  resources :deals
  resources :roles

end

app/models/contract.rb
require 'carrierwave/orm/activerecord'
class Contract < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :project
  belongs_to :partyb
  belongs_to :paytype
  has_many :deals
  default_scope -> { order(created_at: :desc) }
  
  validates_presence_of  :name, presence: true, :message => "合同名称不能为空！"
  validates_presence_of  :code, presence: true, :message => "合同代码不能为空！"
  validates_uniqueness_of :code, :message => "合同代码不能相同！"
  validates :total, numericality: { greater_than: 0 },  allow_blank: true
  validates :surplus, numericality: { greater_than: 0 },  allow_blank: true
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  def index
	@contracts = Contract.paginate(page: params[:page])
  end
  
  def show
    @contract = Contract.find(params[:id])
    @deals = @contract.deals.paginate(page: params[:page])	
  end
  
  def new
	# @projects = Project.all
	# @partybs = Partyb.all
	@contract = Contract.new
  end
  
  def create
    @contract = Contract.new(contract_params)
	@project = Project.find(@contract.project_id)
	if @contract.paytype_id == 1
		sf= 's'
	elsif @contract.paytype_id == 2
		sf = 'f'
	end
	ctype = @project.ProjectType.code
	ctypenum = 1
	Contract.all.each do |cont|
		if cont.created_at.year == Time.now.year
			if cont.project.ProjectType_id == @project.ProjectType_id
				ctypenum = ctypenum + 1
			end
		end
	end
	if Contract.first.nil?
		ls = 1	
	else

	   if Contract.first.created_at.year == Time.now.year
			ls = Contract.first.id + 1
		else
			ls = 1
		end
	end
	@contract.code = Time.now.strftime("%Y") + sf + ctype.to_s + ctypenum.to_s + '-' + ls.to_s

	if @contract.save
      flash[:success] = "合同已经新建!"
      redirect_to contracts_url
    else
      render 'new'
    end
  end

  def edit
    @contract = Contract.find(params[:id])
  end
   
  def update
    @contract = Contract.find(params[:id])
    if @contract.update_attributes(contract_params)
      flash[:success] = "合同信息已修改！"
      redirect_to contracts_url
    else
      render 'edit'
    end
  end
  
  private

    def contract_params
      params.require(:contract).permit(:name, :partyc, :paytype_id, :director,:director_tel,:total,:surplus,:detail,:sign_time,:time_limit,:project_id,:partyb_id,:avatar)
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_contract.html.erb
  <tr>
    <th><%= link_to contract.name, contract %></th>
    <th><%= contract.code %></th>
	<th><%= contract.project.name %></th>
	<th><%= contract.partyb.name %></th>
	<th><%= contract.total %></th>
	<th><%= contract.sign_time %></th>
	<th><%= contract.time_limit %></th>
	<th><%= contract.paytype.name %></th>
	<th><%= link_to "修改", edit_contract_path(contract) %></th>
  </tr>

app/views/contracts/_form_contract.html.erb
<div class="row">
    <%= form_for(@contract) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
		<%= f.label "合同名称" %>:
		<%= f.text_field :name ,:class => 'form-control'%>
	  <div class="row">
		<div class="col-xs-5">
		  <%= f.label "项目名称" %>
		  <%= collection_select(:contract ,:project_id , Project.all, :id, :name,:class => 'form-control') %>
		  <%= f.label "收/付" %>:
		  <%= collection_select(:contract ,:paytype_id , Paytype.all, :id, :name,:class => 'form-control') %>
		</div> 
		
		
		<div class="col-xs-5 col-md-offset-2">
		  <%= f.label "选择对方单位" %>
		  <%= collection_select(:contract ,:partyb_id , Partyb.all, :id, :name,:class => 'form-control') %>	
 		  <%= f.label "对方负责人" %>:
		  <%= f.text_field :director ,:class => 'form-control'%>	 
		</div>  
	</div>  

	<div class="row">
		<div class="col-xs-5">
		  <%= f.label "第三方" %>:
		  <%= f.text_field :partyc ,:class => 'form-control'%>	  

	    </div>
		<div class="col-xs-5 col-md-offset-2">	  
		  <%= f.label "负责人电话" %>:
		  <%= f.text_field :director_tel ,:class => 'form-control'%>

	    </div>
	</div>  
	
	<div class="row">
		<div class="col-xs-5">
		  <%= f.label "合同总价（单位：元）" %>:
		  <%= f.text_field :total ,:class => 'form-control'%>
		  <%= f.label "费用明细" %>:
		  <%= f.text_area :detail ,:class => 'form-control'%>	
	    </div>
		<div class="col-xs-5 col-md-offset-2">	 
		  <%= f.label "合同期限（单位：天）" %>:
		  <%= f.text_field :time_limit ,:class => 'form-control'%>			
		  <%= f.label "签订时间" %>
  		  <%= f.date_select :sign_time,use_month_numbers: true %>		  
		</div>
	</div>   
	<div class="row">	
			 <label>上传合同（合同格式应为jpg或者pdf格式！）:</label>
			 <%= @contract.avatar_identifier if @contract.avatar? %>
			 <%= f.file_field :avatar ,:class => 'form-control'%>
	</div> 
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
</div>

app/views/contracts/edit.html.erb
<% provide(:title, '修改合同信息') %>
<% provide(:button_text, '保存') %>
<h1>修改合同信息</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_contract' %>
  </div>
</div>

app/views/contracts/index.html.erb
<div class="row">	
	<h1>合同清单</h1>
	<section class="user_info col-md-10 col-md-offset-1">
	<h3>
		<%= link_to "新建合同" ,new_contract_path %> |
		<%= link_to "业务往来单位信息记录", partybs_path %>	|
		<%= link_to "收/付款记录", deals_path %>	
	</h3>
	<hr>	
	<%= will_paginate @contracts %>
	<table class="table table-striped table-bordered">
	  <tr>
		<th>合同名称</th>
		<th>合同编号</th>
		<th>项目编号</th>
		<th>对方名称</th>
		<th>合同总价</th>
		<th>签订时间</th>
		<th>工期</th>
		<th>收付类型</th>
		<th>修改</th>
	  </tr>
	  <% @contracts.each do |contract| %>
		<%= render contract %>
	  <% end %>
	</table>
	<%= will_paginate @contracts %>
    </section>

</div>

app/views/contracts/new.html.erb
<% provide(:title, '新建合同') %>
<% provide(:button_text, '保存') %>
<div class="row">
<h1>新建合同</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_contract' %>
  </div>
</div>

app/views/contracts/show.html.erb
<% provide(:title, "合同信息") %>
<% provide(:button_text, '保存') %>
<h1>修改合同信息</h1>
<div class="row">
  <aside class="col-md-4">
    <%= render 'form_contract' %>
	<hr>
	合同收/付情况：
	<hr>
    <% if @contract.deals.any? %>
        <%= render @deals %>
		<%= will_paginate @deals %>
	<% end %>
  </aside>
  <div class="col-md-8">
    <% if @contract.avatar? %>
		<iframe src=<%= @contract.avatar_url %> width="100%" height="780" style="border: none;"> </iframe>
	<% else %>
        <li><%= link_to "添加合同", edit_contract_path(@contract) %></li>
    <% end %>
  </div>
</div>