config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :worklogs,          only: [:create, :destroy]
  resources :projects
  resources :implements
  resources :partakers
  resources :plans
  resources :partybs
  resources :contracts
  resources :deals
  resources :roles

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :ProjectType
  belongs_to :ProjectStatus
  has_many :implements, dependent: :destroy
  has_many :partakers, dependent: :destroy
  has_many :plans, dependent: :destroy
  has_many :contracts
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates_presence_of :name, :message => "项目名称不能为空"
  validates_presence_of :code, :message => "项目编号不能为空"
  validates_uniqueness_of :code , :message => "项目编号必须唯一"
  validates_presence_of :user_id, :message => "项目负责人不能为空" 
  validates_presence_of :ProjectStatus_id, :message => "项目状态不能为空" 
  validates_presence_of :ProjectType_id, :message => "项目类型不能为空" 
  validates_presence_of :start_time, :message => "项目开始时间不能为空" 
  validate :end_time_after_start_time

  private
  
	  #检查结束时间在开始时间之后.
	  def end_time_after_start_time
		if start_time > end_time
		   errors[:end_time] << "结束时间需要在开始时间之后"
		end
	  end 

end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
  has_many :projects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in_user

   def new
	  @project = Project.new
	  if Project.last.nil?
  		@project.monthid = 1
	  else
		  last = Project.first
		  last_month = last.code[4,6]
		  if last_month == Time.now.strftime('%Y%m').to_s
			 @project.monthid = last.monthid + 1
		  else
			 @project.monthid = 1
		  end
	  end
	  strnow = "KLIC"+ Time.now.strftime('%Y').to_s+Time.now.strftime('%m').to_s
	  @project.code = strnow + "-" + @project.monthid.to_s
	  @implement= @project.implements.build
   end
   
  def index
    @projects = Project.paginate(page: params[:page])
  end
  
  def show
    @project = Project.find(params[:id])
  	# @implement= @project.implements.build
    @implements = @project.implements.paginate(page: params[:page])	
    @partakers = @project.partakers.paginate(page: params[:page])
	@plans = @project.plans.paginate(page: params[:page])
  end
  
  def create
    @project = Project.new(project_params)
	if @project.save
      flash[:success] = "项目新建成功!"
      redirect_to projects_url
    else
      render 'new'
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end   
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = "项目已修改！"
      redirect_to projects_url
    else
      render 'edit'
    end
  end
  
  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "删除成功！"
    redirect_to projects_url
  end
 
 
  private

    def project_params
      params.require(:project).permit(:name, :code, :ProjectType_id,
                                   :user_id,:ProjectStatus_id,:monthid,:start_time,:end_time)
    end
	
    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "请登录."
        redirect_to login_url
      end
    end
	
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form_project.html.erb
<div class="row">
    <%= form_for(@project) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
		  <%= f.label "项目名称" %>
		  <%= f.text_field :name,:class => 'form-control' %>
	  <div class="row">
		<div class="col-xs-5">
		  <%= f.label "项目编号" %>:
		  <%= f.text_field :code ,:readonly => true,:class => 'form-control'%>
		  <%= f.hidden_field :monthid ,:class => 'form-control'%>
		</div>  	 
		<div class="col-xs-5 col-md-offset-2">
		  <%= f.label "项目类型" %>
		  <%= collection_select(:project ,:ProjectType_id , ProjectType.all, :id, :name,:class => 'form-control') %>	  
		</div>  
	</div>  

	<div class="row">
		<div class="col-xs-5">
		  <%= f.label "项目负责人" %>
		  <%= collection_select(:project ,:user_id , User.all, :id, :name) %>	
	    </div>
		<div class="col-xs-5 col-md-offset-2">	  
		  <%= f.label "项目状态" %>
		  <%= collection_select(:project ,:ProjectStatus_id , ProjectStatus.all, :id, :name) %>	  
	    </div>
	</div>  
	
	<div class="row">
		<div class="col-xs-5">
		  <%= f.label "项目开始时间" %>
  		  <%= f.date_select :start_time,use_month_numbers: true %>

	    </div>
		<div class="col-xs-5 col-md-offset-2">	  
		  <%= f.label "项目结束时间" %>
		  <%= f.date_select :end_time,use_month_numbers: true %>
		</div>
	</div>    
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
</div>

app/views/projects/_project.html.erb
  <tr>
    <th><%= link_to project.name, project %></th>
    <th><%= project.code %></th>
	<th><%= project.ProjectType.name %></th>
	<th><%= project.user.name %></th>
	<th><%= project.ProjectStatus.name %></th>
	<th><%= project.start_time %></th>
	<th><%= project.end_time %></th>
	<th><%= link_to "删除", project, method: :delete, data: { confirm: "确定删除?" } %></th>
	<th><%= link_to "修改", edit_project_path(project) %></th>
  </tr>

app/views/projects/edit.html.erb
<% provide(:title, '项目情况') %>
<% provide(:button_text, '保存') %>
<h1>修改项目</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_project' %>
  </div>
</div>

app/views/projects/index.html.erb
<% provide(:title, '项目清单') %>
<h1>项目清单</h1>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h3>
		<%= link_to "新建项目", new_project_path  %> |
		<%= link_to "新建部门任务", new_implement_path  %> |
		<%= link_to "新建项目参与人员", new_partaker_path  %> | 
		<%= link_to "新建项目计划", new_plan_path %> 
	</h3>
	<%= will_paginate %>
	<table class="table table-striped table-bordered">
	  <tr>
		<th>项目名称</th>
		<th>项目编号</th>
		<th>项目类型</th>
		<th>项目负责人</th>
		<th>项目状态</th>
		<th>项目开始时间</th>
		<th>项目结束时间</th>
		<th>删除</th>
		<th>修改</th>
	  </tr>
	  <% @projects.each do |project| %>
		<%= render project %>
	  <% end %>
	</table>
	<%= will_paginate %>
  </div>
</div>

app/views/projects/new.html.erb
<% provide(:title, '新建项目') %>
<% provide(:button_text, '保存') %>
<h1>新建项目</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_project' %>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, "项目信息") %>
<div class="row">
	<h1>项目信息</h1>
	<h2><%= link_to "修改项目", edit_project_path(@project) %> | 
	<%= link_to "删除项目", @project, meliod: :delete, data: { confirm: "确定删除?" } %>
	</h2>
</div>
<div class="row">

  <div class="col-md-4 col-md-offset-1">
	
  	<h3>
		<li>项目名称：<%= @project.name %></li>
		<li>项目编号：<%= @project.code %></li>
		<li>项目类型：<%= @project.ProjectType.name %></li>
		<li>项目负责人：<%= @project.user.name %></li>
		<li>项目状态：<%= @project.ProjectStatus.name %></li>
		<li>项目开始时间：<%= @project.start_time %></li>
		<li>项目结束时间：<%= @project.end_time %></li>
	</h3>

  </div>
  <div class="col-md-7">
    <section class="user_info">
	实施部门：
    <% if @project.implements.any? %>
      <ol class="worklogs">
        <%= render @implements %>
      </ol>
      <%= will_paginate @implements %>
    <% end %>
	</section>
	<section class="user_info">
	参与人员：
    <% if @project.partakers.any? %>
      <ol class="worklogs">
        <%= render @partakers %>
      </ol>
      <%= will_paginate @partakers %>
    <% end %>
    </section>
	<section class="user_info">
	本项目时间计划：
    <% if @project.plans.any? %>
      <ol class="worklogs">
        <%= render @plans %>
      </ol>
      <%= will_paginate @plans %>
    <% end %>
    </section>
  </div>
</div>