config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :worklogs,          only: [:create, :destroy]
  resources :projects
  resources :implements
  resources :partakers
  resources :plans
  resources :partybs
  resources :contracts
  resources :deals
  resources :roles

end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
	validates_uniqueness_of :name , :message => "角色名称不能相同！"
	validates_uniqueness_of :id , :message => "角色ID不能相同！"
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  # before_action :admin_user, only: [:update, :destroy]
  def index
	@roles = Role.all
  end

  def new
	@role = Role.new
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      flash[:success] = "角色已建立!"
      redirect_to roles_path 
	else
       render 'new'
    end
  end 
  
  def edit
	@role = Role.find(params[:id])
  end
 
  def update
    @role = Role.find(params[:id])
    if @role.update_attributes(role_params)
      flash[:success] = "角色已修改！"
      redirect_to roles_path 
    else
      render 'edit'
    end
  end

  def destroy
    Role.find(params[:id]).destroy
    flash[:success] = "删除成功！"
    redirect_to roles_path
  end
  
  private

    def role_params
      params.require(:role).permit(:id,:name,:definition)
    end
   # Confirms an admin user the role equel 0.
    # def admin_user
	  # @user=User.find_by(id:session[:user_id])
      # redirect_to(root_url) unless role_admin?
    # end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
    <%= form_for(@role) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
	
	
      <%= f.label "角色ID" %>
      <%= f.text_field :id,:class => 'form-control'%>

      <%= f.label "输入角色名（不可重复）" %>
      <%= f.text_field :name,:class => 'form-control' %>
	  
      <%= f.label "角色定义" %>
      <%= f.text_field :definition,:class => 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

app/views/roles/_role.html.erb
<li>
  <%= link_to user.name, user %>
    | <%= link_to "删除", user, method: :delete, data: { confirm: "确定删除?" } %>
	| <%= link_to "修改", edit_user_path(user) %>
</li>

app/views/roles/edit.html.erb
<% provide(:title, '修改角色') %>
<% provide(:button_text, '保存') %>
<h1>修改角色</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/roles/index.html.erb
<% provide(:title, '角色用户') %>
<h1>角色管理</h1>
<hr>
<h2><%= link_to "新建角色", new_role_path %></h2>
<hr>
  <% if @roles.any? %>
	<% @roles.each do |role| %>
		<li>角色序号：<%= role.id %>；角色名称：<%= role.name %>；角色定义：<%= role.definition %>。    | <%= link_to "删除", role, method: :delete, data: { confirm: "确定删除?" } %> | <%= link_to "修改", edit_role_path(role) %></li>
	<% end %>
  <% end %>

app/views/roles/new.html.erb
<% provide(:title, '新建角色') %>
<% provide(:button_text, '保存') %>
<h1>新建角色</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>